---
- hosts: windows
  gather_facts: False
  tasks:

  - name: Identify if the server use inetd
    stat:
      path: /etc/inetd.conf
    register: exist_inetd
  - name: Comment the 'login' line in /etc/inetd.conf
    lineinfile:
      path: '/etc/inetd.conf'
      regexp: '(?i)^(login.*)'
      line: '#\1'
      backrefs: yes
      state: present
    notify:
    - Restart inetd
    when:  exist_inetd.stat.exists == True

  - name: Recursively find .rhosts in home directories
    find:
      paths: /home
      patterns: ".rhosts"
      recurse: true
      hidden: true
      file_type: any
    register: users_rhosts

