---
- hosts: all
  gather_facts: False
  tasks:

  - name: Identify if the server use inetd
    stat:
      path: /etc/inetd.conf
    register: exist_inetd
  - name: Comment the 'login' line in /etc/inetd.conf
    lineinfile:
      path: '/etc/inetd.conf'
      regexp: '(?i)^(login.*)'
      line: '#\1'
      backrefs: yes
      state: present
    notify:
    - Restart inetd
    when:  exist_inetd.stat.exists == True

  - name: Recursively find .rhosts in home directories
    find:
      paths: /home
      patterns: ".rhosts"
      recurse: true
      hidden: true
      file_type: any
    register: users_rhosts

  - name: Delete .rhosts in root home directory
    file:
      path: "/root/.rhosts"
      state:  absent
    register: root_rhosts

#  - name: Print a debug message
#    debug:
#      msg: "{{ root_rhosts }}"

  - name: Delete all .rhosts in users home directories
    file:
      path: "{{ item.path }}"
      state:  absent
#    loop: "{{ users_rhosts.files }}"
    with_items: " {{ users_rhosts.files }} "
#    loop_control:
#      label: "{{ item.path }}"

  handlers:
  - name: Restart inetd
    service:
      name: inetd
      state: restarted
